version: "3.9"
services:
  app:
    image: nginx:alpine
    ports:
      - "7799:80"
    volumes:
      - "web_data:/usr/share/nginx/html"
  cow:
    image: olasz13/pythonka:latest
    volumes:
      - "web_data:/root/html"
volumes:
  web_data: